@extends('layouts.app')

@section('content')
<div class="shadow-sm container p-3 rounded" style="background: rgba(255,255,255,0.2)">
    <div class="bg-white p-4 mb-3">
        <h1>Histórico Rede</h1>
        <br><br>
        <p style="text-align:justify">
                <span style="padding-left:5em"> A Rede de Orgânicos de Osório foi criada a partir de reflexões sobre a alimentação, em destaque para a origem e a forma como os alimentos são produzidos no meio rural. Reconhece-se que o modelo hegemônico e convencional de agricultura, baseado no uso desenfreado de agrotóxicos, traz inúmeros impactos negativos, é insustentável social e ambientalmente, além de colocar em risco a saúde de quem produz e de quem consome. Como alternativa a esse modelo, (res) surgem vários outros, alguns existentes desde os primórdios da agricultura realizada pela humanidade e outros que estão sendo construídos por milhões de agricultores pelo mundo afora. </span>
                No nosso município e no Litoral Norte, também há produtores de cultivos orgânicos, que além de plantarem para si, sua família, possuem como sustento a venda de dezenas de alimentos. Vários agricultores e suas famílias possuem um trabalho de pioneirismo, histórico e reconhecido por importantes setores da comunidade. Entretanto, há gargalos a serem identificados e resolvidos como a comercialização que é um dos principais entraves para o desenvolvimento da atividade em nível dos agricultores, como também do reconhecimento e expansão da agricultura familiar orgânica. A partir disso surge a necessidade de buscar maneiras de valorização dos produtores e os seus produtos. <br><br> </span>
                <span style="padding-left:5em"> Assim em meados de 2016 iniciou-se um projeto, formado por um grupo organizado de agricultores orgânicos, consumidores e Emater/RS-Ascar. O trabalho feito em rede através de um projeto-piloto, onde participaram os alunos da turma de Pós-Graduação Lato Sensu em Meio Ambiente e Biodiversidade da Universidade Estadual do Rio Grande do Sul (UERGS), unidade Litoral Norte, localizada em Osório. O projeto consistia no envio de uma lista de produtos produzidos pelos agricultores e disponíveis na semana, como também na época do ano, via rede social whatsapp (terças-feiras). Os alunos interessados “montavam a sua cesta” de produtos, e encaminhavam seus pedidos até quinta-feira ao meio-dia. Os agricultores possuíam um dia e meio para fazer a colheita e elaboração das cestas. A entrega era feita na unidade da universidade aos sábados pela manhã, um dos dias letivos da turma. Isso se realizou até a última aula, em dezembro de 2016. <br><br> </span>
                <span style="padding-left:5em"> Concomitantemente ao grupo da UERGS, a Rede de Orgânicos ia agregando outros consumidores interessados que retiram suas cestas na Feira dos Produtores de Osório que ocorre semanalmente aos sábados pela manhã, cujo objetivo é reduzir custos de logística para os agricultores. <br><br> </span>
                <span style="padding-left:5em"> Com o trabalho que está sendo realizado há o envolvimento dos consumidores tanto na organização das cestas quanto na entrega, além de reuniões semanais entre agricultores e consumidores (todas segundas-feiras na sede da Emater/RS-Ascar em Osório), para juntos resolverem os problemas e de aproximação entre ambas as partes. Outras atividades de integração já ocorreram, em destaque duas visitas a propriedades de dois agricultores, ainda em 2016. <br><br> </span>
                <span style="padding-left:5em"> No ano de 2017, dando seguimento as atividades, e de acordo com o cronograma da Rede de Orgânicos foram promovidas diversas atividades, entre elas: <br> </span>
                <span style="padding-left:5em"> – Visitas dos consumidores as propriedades dos produtores Ricardo Bertoli e Euclides Duarte Barcelos; <br> </span>
                <span style="padding-left:5em"> – Oficina de culinária em parceria com o Instituto Federal do Rio Grande do Sul – Campus Osório; <br> </span>
                <span style="padding-left:5em"> – Participação na Semana do Meio Ambiente de Osório, com promoção da Secretaria Municipal de Meio Ambiente, Agricultura e Pecuária, através do cine-debate, realizado na Escola Estadual de Ensino Médio Idelfonso Simões Lopes – Escola Rural – aberto ao público, com o documentário “O veneno está na mesa”, com a participação do professor Dr. Jairo Bolter (UFRGS – Campus Litoral Norte);  <br></span>
                <span style="padding-left:5em"> – Visita à Chácara Sol Nascente no município de Sentinela do Sul, uma experiência na área da Agroecologia. O solo da área, degradado, vem sendo recuperado com técnicas de biodinâmica e implantação de uma agrofloresta;  <br></span>
                <span style="padding-left:5em"> – Participação na Feira de Biodiversidade em Três Cachoeiras; <br></span>
                <span style="padding-left:5em"> – Participação na Semana Acadêmica do Curso de Tecnologia em Processos Gerenciais/20017 do IFRS – Campus Osório; <br></span>
                <span style="padding-left:5em"> – Parceria com o Núcleo de Estudos Agroecológicos (NEA) da UFRGS – Campus Litoral Norte; <br></span>
                <span style="padding-left:5em"> – Parceria com os docentes e funcionários do Campus Litoral Norte da Universidade Federal do Rio Grande do Sul (UFRGS/CLN) com a entrega de cestas nas quintas-feiras; <br></span>
                <span style="padding-left:5em"> – Parceria com o IFRS – Campus Osório, através do Projeto de extensão “Rede de orgânicos de Osório: um mercado de proximidade e de reciprocidade”. Neste projeto a Rede de Orgânicos foi contemplada com uma verba onde foi possível uma parceria com a Comunidade Mbya Guarani da Aldeia Kuaray Rese (Sol Nascente), para a confecção de balaio de palha de taquara como forma de substituição às embalagens plásticas na entrega das cestas. Outra contribuição do projeto foi a confecção de banners institucionais da Rede; <br></span>
                <span style="padding-left:5em"> – Participação nas duas edições da Ecofeira promovidas pela Secretária de Meio Ambiente, Agricultura e Pecuária de Osório; <br></span>
                <span style="padding-left:5em"> – Participação semanal, às quartas-feiras pela manhã, na Feira de Xangri-lá, e à tarde na Feira da Assembleia Legislativa e aos sábados na Feira da Praça da Encol do bairro Petrópolis em Porto Alegre.  <br></span>
                <span style="padding-left:5em"> Os produtores pertencentes à Rede são integrantes da OPAC ou da ECOVIDA, sendo as duas certificações participativas. Há uma produtora em período de certificação. Um ponto importante a ser destacado é que a rede é uma forma de escoar o excedente de produção do agricultor, em que os produtos que antes eram perdidos na propriedade passaram a ser consumidos. <br></span>
        </p>
    </div>
</div>
@endsection